package seed

import (
	"github.com/labstack/gommon/log"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"sipamit-be/api/device/repo"
	"sipamit-be/internal/pkg/doc"
	"time"
)

func FingerPrint(db *mongo.Database) {
	fpsRepo := repo.NewFingerPrintRepository(db)

	count, _ := fpsRepo.Count()
	if count > 0 {
		log.Info("Fingerprint already seeded")
		return
	}

	err := fpsRepo.InsertMany(fps)
	if err != nil {
		log.Errorf("Failed to seed fingerprint: %v", err)
	}
	log.Info("Fingerprint seeded")
}

var fps = []repo.FingerPrint{
	{
		ID:        bson.NewObjectID(),
		Nama:      "POLIKLINIK",
		Lokasi:    "PH1",
		Kode:      "PH1-FSREVOWF-206BNC-01",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING A.B 1",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-02",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING A.B 2",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-03",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT E",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-04",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING C.D.E",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANTT-05",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING C",
		Lokasi:    "PH1",
		Kode:      "PH1-FSREVOWDV-240BNC-06",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING D",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-07",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PACKING A.B.C.D.E",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-08",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. KT. JAHIT E",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-09",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "DESIGN BAWAH",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-10",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "POS TENGAH (OFFICE)",
		Lokasi:    "PH1",
		Kode:      "PH1-FSREVOWDV-240BNC-11",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "GUDANG JADI LUAR",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-12",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "GUDANG KARTON",
		Lokasi:    "PH1",
		Kode:      "PH1-FSREVOWDV-240BNC-13",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING. PACKING F",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-14",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KT. PLONG. JAHIT F1-F3",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-15",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT F4-F7",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-16",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT D",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-17",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT B",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-18",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT A",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-19",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. KT A",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-20",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. KT B",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-21",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "SABLON ATAS. INSOLE",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-22",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT. PLONG. D. E",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-23",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. JAHIT. D",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-24",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG C",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-25",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KT C",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-26",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "SABLON. PISAU",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-27",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "G BAHAN. JK. BANGUNAN. BENGKEL. LEM",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-28",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "OUTSOLE A.B. SPET",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-29",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "OUTSOLE C. SESEP",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-30",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. KT. JAHIT H 1",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-31",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG. KT. JAHIT H 2",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-32",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "FOXING. LAMINATING. STRIMMING 1",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-33",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "FOXING. LAMINATING. STRIMMING 2",
		Lokasi:    "PH1",
		Kode:      "PH1-FSMULTIMEDIA-34",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING H",
		Lokasi:    "PH1",
		Kode:      "PH1-FSELEGANT-35",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "OFFICE PH2",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-001",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT A2 (A5-A8)",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-002",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "DESIGN. JAHIT A1",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT REVOWDV-240BNC-003",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG B.KT B.PRINTING. JAHIT C1 (C1-C4)",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-004",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT B2 (B5-B8)",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-005",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT C2 (C5-C8)",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-006",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KT C . PLONG C",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT MULTIMEDIA-007",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG A. KT A",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-008",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING A",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-009",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT A1 (A1-A4). SAMPLES",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT REVOWDV-240BNC-010",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING C",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-011",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING B",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-012",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT B1 (B1-B4)",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-013",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "QA. PACKING. GD.BAHAN",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT ELEGANT-014",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "FINGER FACE A",
		Lokasi:    "PH2",
		Kode:      "PH2-FINGERSPOT NEW HYBRIDPRO-015",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LASTING D",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT ELEGANT-016",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT D2 (D5-D8).PLONG INSOLE. OUTSOLE",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT REVOWDV-240BNC-017",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "PLONG D. KT D",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT ELEGANT-018",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "JAHIT D1 (D1-D4). LAMINATING",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT ELEGANT-019",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "OUTSOLE.INSOLE.PACKING 2",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT REVOWDV-240BNC-020",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "FINGER FACE B",
		Lokasi:    "PH3",
		Kode:      "PH3-FINGERSPOT NEW HYBRIDPRO-021",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
}
