package seed

import (
	"github.com/labstack/gommon/log"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"sipamit-be/api/device/repo"
	"sipamit-be/internal/pkg/doc"
	"time"
)

func KomputerPH1(db *mongo.Database) {
	kph1Repo := repo.NewKomputerPH1Repository(db)

	count, _ := kph1Repo.Count()
	if count > 0 {
		log.Info("Komputer ph1 already seeded")
		return
	}

	err := kph1Repo.InsertMany(komputerPh1)
	if err != nil {
		log.Errorf("Failed to seed komputer ph1: %v", err)
	}
	log.Info("Komputer ph1 seeded")
}

var komputerPh1 = []repo.KomputerPH1{
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LINA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-001",
		Monitor:   "PH1-DELLE2016HV-001",
		CPU:       "Intel Celeron",
		RAM:       "4 GB",
		Internal:  "HDD: 500GB",
		Lokasi:    "UMUM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DRAFTER",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-037",
		Monitor:   "PH1-ASUSVX207-102",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 500GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER NADA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-004",
		Monitor:   "PH1-DELLE2016HV-004",
		CPU:       "Intel Core2 Duo",
		RAM:       "4 GB",
		Internal:  "SSD: 500GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RISKA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-003",
		Monitor:   "PH1-DELLE2016HV-003",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER VIOCHA",
		Merk:      "ASUS PRO",
		PC:        "PH1-CPUCOREI3-002",
		Monitor:   "PH1-DELLE2216HV-002",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER TEMMY",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-007",
		Monitor:   "PH1-MONITORDELLE2016HV-007",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER MIA",
		Merk:      "RAKITAN",
		PC:        "PH1-CPUCOREI3-009",
		Monitor:   "PH1-LG19M38A-009",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER CINDY",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-074",
		Monitor:   "PH1-LG19M38A-009",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD : 300 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP PETER",
		Merk:      "DELL INSPIRON  3501",
		PC:        "PH1-LAPTOPDELLINSPIRON3501-009",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SDD : 256 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER CHENNEDY",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-010",
		Monitor:   "PH1-MONITORDELLE2216HV-010",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER NATASHA",
		Merk:      "RAKITAN AEROCOOL",
		PC:        "PH1-CPUCOREI3-006",
		Monitor:   "PH1-HPV194-006",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DANIS",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-105",
		Monitor:   "PH1-LG19M38A-105",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP NANCY",
		Merk:      "ASUS",
		PC:        "PH1-LAPTOPASUSX555Q-003",
		Monitor:   "-",
		CPU:       "AMD A12",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "EXIM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AYU",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-012",
		Monitor:   "PH1-MONITORLG20MP48A-012",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "250GB HDD+SSD:500 GB",
		Lokasi:    "PPIC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER EVA",
		Merk:      "DELL OPTIFLEX 7060",
		PC:        "PH1-CPUCOREI5-014",
		Monitor:   "PH1-MONITORLG20M35A-013",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "IE",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER KARINA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-013",
		Monitor:   "PH1-MONITORLG19M35AA-014",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD:500 GB+120GB",
		Lokasi:    "PPIC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER VINA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-046",
		Monitor:   "PH1-MONITORSAMSUNGS19A100N-046",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB+SSD 500GB",
		Lokasi:    "PPIC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FATIN",
		Merk:      "Rakitan Futura Black",
		PC:        "PH1-CPUCOREI3-015",
		Monitor:   "PH1-MONITORDELLE2219HN-015",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 1TB + SSD 500GB",
		Lokasi:    "PPIC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ATIK",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-016",
		Monitor:   "PH1-MONITORDELLS2261HC-016",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD:250GB + SSD 500GB",
		Lokasi:    "PPIC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LILA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-074",
		Monitor:   "PH1-LGFLATW1642S-017",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AINIYA",
		Merk:      "DELL",
		PC:        "PH1-CPUCOREI5-035",
		Monitor:   "PH1-LG24MP58VQ-035",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ELY",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCORE2DUO-023",
		Monitor:   "PH1-LG22MK400H-019",
		CPU:       "INTEL CORE2DUO",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ARUM",
		Merk:      "Rakitan Enlight",
		PC:        "PH1-CPUCOREI3-018",
		Monitor:   "PH1-LG20M35-018",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB + SSD 500GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ANI",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI7-021",
		Monitor:   "PH1-MONITORTOSIBHA2451-021",
		CPU:       "Intel Core I7",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DHIMA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-022",
		Monitor:   "PH1-LGFLATW1642S-022",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ETI",
		Merk:      "Rakitan ATIK",
		PC:        "PH1-CPUCOREI5-101",
		Monitor:   "PH1-MONITORLG22M38H-023",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RICKY",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI5-025",
		Monitor:   "PH1-MONITORDELLE1916HV-101",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ERIS",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-024",
		Monitor:   "PH1-LG19M38A-019",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB + 120GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP BU GIA",
		Merk:      "HP VICTUS",
		PC:        "PH1-HPVICTUS-005",
		Monitor:   "-",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD : 512 GB",
		Lokasi:    "MANAGER",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER APRIL",
		Merk:      "Rakitan ERSYS",
		PC:        "PH1-CPUCOR2DUO-017",
		Monitor:   "PH1-BENQT52WA-017",
		CPU:       "INTEL CORE 2 DUO",
		RAM:       "3 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP META",
		Merk:      "ASUS P1440FA",
		PC:        "PH1-LAPTOPASUSP1440FA-008",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 256 GB",
		Lokasi:    "DC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ENDAH",
		Merk:      "DELL INSPIRON",
		PC:        "PH1-CPUCOREI3-066",
		Monitor:   "PH1-DELLE2016HV-020",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB | HDD: 1 TB",
		Lokasi:    "PEMBELIAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER IZZATIR",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-025",
		Monitor:   "PH1-HPV194-025",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ANGEL",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-104",
		Monitor:   "PH1-MONITORLG20M35A-026",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER IRMA",
		Merk:      "DELL OPTIFLEX 7060",
		PC:        "PH1-COREI5-027",
		Monitor:   "PH1-HPV194-027",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FENI",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-000",
		Monitor:   "PH1-LGW1642S-073",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "M2 : 250 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AVI",
		Merk:      "Rakitan Futura Black",
		PC:        "PH1-CPUCOREI3-006",
		Monitor:   "PH1-HPV194-011",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SHIVA",
		Merk:      "ACER VERITON N4640G",
		PC:        "PH1-CPUCOREI5-029",
		Monitor:   "PH1-LG19M38A-029",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 256 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER KARTIKA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-030",
		Monitor:   "PH1-MONITORLGFLATRONW2252TA-030",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DEBORA",
		Merk:      "Rakitan ERSYS",
		PC:        "PH1-CPUCOREI3-00",
		Monitor:   "PH1-LG19M38A-044",
		CPU:       "ATHLON X2",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER HANUM",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-CPUCOREI5-115",
		Monitor:   "PH1-HPV194-026",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN SOP",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER YOSI",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI5-031",
		Monitor:   "PH1-MONITORDELLE2219HN-031",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 250 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER HERA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI7-032",
		Monitor:   "PH1-MONITORDELLE2216HC-032",
		CPU:       "Intel Core I7",
		RAM:       "8 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ROSSA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-033",
		Monitor:   "PH1-MONITORHPCQ1569X-033",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP RATNA",
		Merk:      "LENOVO",
		PC:        "PH1-LENOVOTB14S-009",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ALUAN",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-CPUCOREI5-028",
		Monitor:   "PH1-LG20M35SA-034",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AGUSTINA",
		Merk:      "RAKITAN TAIWAN POWER TRAIN",
		PC:        "PH1-CPUCOREI5-035",
		Monitor:   "PH1-MONITORLG24MP58VQ-035",
		CPU:       "Intel Core I5",
		RAM:       "16 GB",
		Internal:  "HDD :1 TB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ULIL",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-036",
		Monitor:   "PH1-MONITORLG20MP47A-036",
		CPU:       "Intel Core I5",
		RAM:       "24 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SUSI",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-103",
		Monitor:   "PH1-MONITORLG24MP58VQ-037",
		CPU:       "Intel Core I5",
		RAM:       "16 GB",
		Internal:  "HDD: 500 GB+SSD 500GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ZHU (DIPAKAI BU IRA CRIME)",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI7-038",
		Monitor:   "PH1-MONITORLGFLATRONL1742SE-038",
		CPU:       "Intel Core I7",
		RAM:       "8 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "DESIGN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-114",
		Monitor:   "PH1-LGW1642S-062",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RASMINI",
		Merk:      "ASUS PRO",
		PC:        "PH1-CPUCOREI3-045",
		Monitor:   "PH1-MONITORDELLE2016HV-045",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SUCI",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-041",
		Monitor:   "PH1-MONITORLG20MP48A-041",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RENA",
		Merk:      "Intel NUC",
		PC:        "PH1-CPUCOREI3-042",
		Monitor:   "PH1-MONITORDELLE2016HV-042",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 250 GB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RACHEL",
		Merk:      "HP",
		PC:        "PH1-CPUCOREI3-040",
		Monitor:   "PH1-LGW1642S-062",
		CPU:       "Intel Core I3",
		RAM:       "2 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER UBAI",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI7-044",
		Monitor:   "PH1-LG20M35-075",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB + 8 TB HDD",
		Lokasi:    "IT",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SERVER TPB",
		Merk:      "RAINER",
		PC:        "PH1-INTELXEONE3-062",
		Monitor:   "-",
		CPU:       "Intel XEON E3",
		RAM:       "8 GB",
		Internal:  "HDD: 2 TB",
		Lokasi:    "IT",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP MERTHA",
		Merk:      "DELL VOSTRO 3458",
		PC:        "PH1-LAPTOPDELLVOSTRO3458-006",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "SAFETY K3",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER VALEN",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-CPUCOREI5-099",
		Monitor:   "PH1-MONITORDELLE2216HV-097",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "SAFETY K3",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP PAK AGUS QA LAB",
		Merk:      "LENOVO",
		PC:        "PH1-LENOVOIDEAPAD3-004",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "8 GB",
		Internal:  "SSD: 512 GB",
		Lokasi:    "QA LAB LABORATORY",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LILIS",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCELERON-049",
		Monitor:   "PH1-HPV194-049",
		CPU:       "INTEL CELERON",
		RAM:       "2 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "QA LAB",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ANISA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-076",
		Monitor:   "PH1-HPV194-111",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "QA LAB",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LINDA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-COREI3-076",
		Monitor:   "PH1-HPV194-011",
		CPU:       "Intel Core I3",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "QA LAB",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER IRA RAHMA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-113",
		Monitor:   "PH1-HPV194-114",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "QA LAB",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FIDA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREi3-010",
		Monitor:   "PH1-MONITORLG19M38A-006",
		CPU:       "Intel Core I3",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB 150GB HDD",
		Lokasi:    "QA LAB LABORATORY",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ATHIKA",
		Merk:      "Rakitan TOMICO",
		PC:        "PH1-CPUCOREI3-050",
		Monitor:   "PH1-MONITORLG22M38H-050",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER NORMA",
		Merk:      "HP PRO",
		PC:        "PH1-CPUCOREI5-051",
		Monitor:   "PH1-MONITORDELLE2216HV-051",
		CPU:       "Intel Core I5",
		RAM:       "2 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FITRI",
		Merk:      "HP PAVILLION",
		PC:        "PH1-CPUCOREI5-052",
		Monitor:   "PH1-MONITORHP20VX-052",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SUSWATI (RayChain)",
		Merk:      "Rakitan ARMAGGEDON",
		PC:        "PH1-CPUCOREI5-103",
		Monitor:   "PH1-MONITORDELLS2421HN-052",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD: 500GB+3TB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ERNA",
		Merk:      "Rakitan ARMAGGEDON",
		PC:        "PH1-CPUCOREI5-054",
		Monitor:   "PH1-DELL2219HW-052",
		CPU:       "Intel Core2Duo",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ERIZA",
		Merk:      "DELL",
		PC:        "PH1-CPUCOREI3-055",
		Monitor:   "PH1-DELL2219HW-055",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ENDAH",
		Merk:      "Rakitan GIGABYTE",
		PC:        "PH1-CPUCOREI5-056",
		Monitor:   "PH1-MONITORHPP191-056",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "HDD: 250 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER EKA",
		Merk:      "DELL INSPIRON",
		PC:        "PH1-CPUCOREI3-058",
		Monitor:   "PH1-MONITORLG22M38H-058",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SERVER AJC",
		Merk:      "RAINER",
		PC:        "PH1-INTELXEONE5606-060",
		Monitor:   "PH1-LG20MK48A-059",
		CPU:       "Intel XEON E5606",
		RAM:       "8 GB",
		Internal:  "HDD: 1.7 TB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DEWI",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-061",
		Monitor:   "PH1-LG20MK48A-063",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 240 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER NENI",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-063",
		Monitor:   "PH1-LG22MK400H-057",
		CPU:       "Intel Core I3",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER IKA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-064",
		Monitor:   "PH1-LG22M38H-062",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LUSI",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-065",
		Monitor:   "PH1-LG19M38A-063",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER UMI",
		Merk:      "PH1-CPUCOREI5-073",
		PC:        "PH1-CPUCOREI5-073",
		Monitor:   "PH1-LG20M35-060",
		CPU:       "Intel Core I5",
		RAM:       "6 GB",
		Internal:  "500GB SSD",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LILIS",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-070",
		Monitor:   "PH1-LG-19M38A-068",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER TUTUT",
		Merk:      "HP Pro 3340",
		PC:        "PH1-CPUCOREI3-057",
		Monitor:   "PH1-MONITORHP191-069",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RINI",
		Merk:      "Rakitan MAXIMAX",
		PC:        "PH1-CPUCOREI3-072",
		Monitor:   "PH1-DELLS2421HN-070",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB + SSD 500GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ROHMA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-CPUCOREI3-070",
		Monitor:   "PH1-LENOVO1922S-067",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DEVI",
		Merk:      "Rakitan ALCATROS",
		PC:        "PH1-CPUCOREi5-113",
		Monitor:   "PH1-LG22M38H-063",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD 500 GB+ 1 TB HDD",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DHILA",
		Merk:      "Rakitan ALCATROS",
		PC:        "PH1-CPUCOREI5-100",
		Monitor:   "PH1-MONITORDELLE211HN-098",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AZURA",
		Merk:      "RAKITAN AEROCOOL",
		PC:        "PH1-CPUCOREI3-109",
		Monitor:   "PH1-LG22M38H-064",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "ACCOUNTING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LIA",
		Merk:      "DELL OPTIFLEX 7060",
		PC:        "PH1-CPUCOREi5-075",
		Monitor:   "PH1-HPV194-073",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "LAPORAN PRODUKSI PH1",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER KIKI",
		Merk:      "DELL OPTIFLEX 7060",
		PC:        "PH1-CPUCOREI5-076",
		Monitor:   "PH1-HPV194-074",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "LAPORAN PRODUKSI PH1",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AGUS (JUKI)",
		Merk:      "Rakitan TSX PRO II",
		PC:        "PH1-CPUCOREI3-078",
		Monitor:   "PH1-MONITORDELLS2216HC-076",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "JAHITKOM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER NINIK",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI5-079",
		Monitor:   "PH1-MONITORASUSVH198-077",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "JAHITKOM",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER WAHYU",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREi5-080",
		Monitor:   "PH1-MONITORLG22MP60VQ-078",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "BORDIR",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER YULITA",
		Merk:      "Rakitan SIMCOOL",
		PC:        "PH1-CPUCOREI3-082",
		Monitor:   "PH1-MONITORDELLE2219HN-080",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "FILM SABLON",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER INTAN",
		Merk:      "ASUS PRO",
		PC:        "PH1-CPUCOREI3-081",
		Monitor:   "PH1-MONITORDELLE2216HV-081",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "FILM SABLON",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ERNA",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-084",
		Monitor:   "PH1-MONITORDELLE2216HVI-082",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "FILM SABLON",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER MESIN FILM",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCELERON-085",
		Monitor:   "PH1-MONITORBENQT51WA-054",
		CPU:       "INTEL CELERON",
		RAM:       "3 GB",
		Internal:  "HDD 500 GB",
		Lokasi:    "FILM SABLON",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP SUSI",
		Merk:      "TOSHIBA SATELITE L645",
		PC:        "PH1-LAPTOPTOSHIBASATELITEL645-010",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "8 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "FILM SABLON",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DAVID",
		Merk:      "Rakitan DAZUMBA",
		PC:        "PH1-CPUCOREI5-083-Nvidia Geforce GTX colorful4 GB",
		Monitor:   "PH1-MONITORDELL2219HN-100",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD: 250 GB",
		Lokasi:    "MATRAS  CNC",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER DJUHEDI",
		Merk:      "Rakitan ALCATROS",
		PC:        "PH1-CPUCOREI3-086",
		Monitor:   "PH1-LG24MK430H-086",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RENY",
		Merk:      "Rakitan ERSYS",
		PC:        "PH1-CPUCOREI3-087",
		Monitor:   "PH1-MONITORLGL20M37A-085",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LENY",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCORE2DUO-088",
		Monitor:   "PH1-MONITORBENQG10HDAL-086",
		CPU:       "Intel Core2Duo",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RINA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-090",
		Monitor:   "PH1-LG19M38A-090",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER KHUSNIA",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-074",
		Monitor:   "PH1-BENQG610HDPL-072",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER PURWANTI",
		Merk:      "LENOVO THINKCENTER M83",
		PC:        "PH1-LENOVOTCM83-086",
		Monitor:   "PH1-MONITORLGL20MP48A-087",
		CPU:       "Intel Core I5",
		RAM:       "10 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "GUDANG BAHAN",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RENA",
		Merk:      "ASUS",
		PC:        "PH1-CPUCOREI5-093",
		Monitor:   "PH1-MONITORLGFLATRONE1642-091",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "GUDANG SOLE",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER ALAN",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-094",
		Monitor:   "PH1-LG19M38A-092",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500GB",
		Lokasi:    "FOXING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER EVELYNNE",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-103",
		Monitor:   "PH1-LG22MK400H-104",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "FOXING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER AUFIA",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-105",
		Monitor:   "PH1-LG22MP410-105",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "FOXING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP WILLY",
		Merk:      "ASUS A416J",
		PC:        "PH1-ASUSA416J-011",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD: 500 GB",
		Lokasi:    "FOXING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP MR. LIE",
		Merk:      "LENOVO V15-IGL",
		PC:        "PH1-LENOVOV15-IGL-012",
		Monitor:   "-",
		CPU:       "INTEL CELERON",
		RAM:       "4 GB",
		Internal:  "SSD: 256 GB",
		Lokasi:    "FOXING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LENI LAMINATING",
		Merk:      "Rakitan SIMBADDA",
		PC:        "PH1-CPUCOREI3-104",
		Monitor:   "PH1-BENQ6700AD-092",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "LAMINATING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FEBRI FOXING WARNA",
		Merk:      "ACER V4220",
		PC:        "PH1-CPUCELERON-086",
		Monitor:   "PH1-ACER- V206HQL-086",
		CPU:       "Intel Celeron",
		RAM:       "4 GB",
		Internal:  "SSD : 256 GB",
		Lokasi:    "FOXING WARNA",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER BC1",
		Merk:      "HP BUILD UP",
		PC:        "PH1-CPUCOREI5-095",
		Monitor:   "PH1-MONITORHP20VX-093",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 1 TB",
		Lokasi:    "BEA CUKAI",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER BC2",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-096",
		Monitor:   "PH1-MONITORDELLE2016HV-094",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "BEA CUKAI",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER CCTV",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCORE2DUO-097",
		Monitor:   "PH1-TCL32S5400-095",
		CPU:       "Intel Core2Duo",
		RAM:       "2 GB",
		Internal:  "HDD: 160 GB",
		Lokasi:    "BEA CUKAI",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER POLIKLINIK",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCORE2DUO-012",
		Monitor:   "PH1-SAMSUNGS19100N-071",
		CPU:       "Intel Core2Duo",
		RAM:       "2 GB",
		Internal:  "SSD: 480 GB",
		Lokasi:    "POLIKLINIK",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER FOTO PERSONALIA BAWAH",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-047",
		Monitor:   "PH1-MONITORBENQT15WA-054",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 250 GB",
		Lokasi:    "HRD",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER RUNI",
		Merk:      "Rakitan AEROCOLL",
		PC:        "PH1-CPUCOREI5-098",
		Monitor:   "PH1-DELLE2219HN-098",
		CPU:       "Intel Core I5",
		RAM:       "8 GB",
		Internal:  "HDD: 500 GB",
		Lokasi:    "DIGITAL PRINT",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LASER 1",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREG3260-084",
		Monitor:   "PH1-MONITORLENOVOT1714A-001",
		CPU:       "-",
		RAM:       "2 GB",
		Internal:  "HDD : 500GB",
		Lokasi:    "LASER",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER LASER 2",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREG3260-085",
		Monitor:   "PH1-MONITORLENOVOT1714A-002",
		CPU:       "-",
		RAM:       "2 GB",
		Internal:  "HDD : 500GB",
		Lokasi:    "LASER",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER PACKING LINE C",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCOREI3-110",
		Monitor:   "PH1-MONITORLGFLATRONW1642S-053",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD :1 TB",
		Lokasi:    "PACKING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER PACKING LINE E",
		Merk:      "Rakitan AEROCOLL",
		PC:        "PH1-CPUCOREI3-111",
		Monitor:   "PH1-MONITORHANSGH191A-049",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 500 GB",
		Lokasi:    "PACKING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER PACKING LINE F",
		Merk:      "Rakitan ARMAGGEDON",
		PC:        "PH1-CPUCOREI3-112",
		Monitor:   "PH1-DELLE1916HV-112",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "SSD : 250 GB",
		Lokasi:    "PACKING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER PACKING LINE H",
		Merk:      "Rakitan",
		PC:        "PH1-CPUCORE2DUO-081",
		Monitor:   "PH1-BENQG610HDPL-086",
		CPU:       "INTEL CORE 2 DUO",
		RAM:       "4 GB",
		Internal:  "SSD : 256 GB",
		Lokasi:    "PACKING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP ACER ASPIRE FOXING STRIMMING",
		Merk:      "ACER ASPIRE",
		PC:        "PH1-LAPTOPACERASPIRE471-001",
		Monitor:   "-",
		CPU:       "Intel Core I5",
		RAM:       "4 GB",
		Internal:  "SSD : 250 GB",
		Lokasi:    "FOXING STRIMMING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP (MEETING)",
		Merk:      "ASUS ASUS A45A",
		PC:        "PH1-LAPTOPASUSA45A-005",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "2 GB",
		Internal:  "HDD: 320 GB",
		Lokasi:    "MEETING",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "LAPTOP NURUL SPAREPART",
		Merk:      "ACER",
		PC:        "PH1-LAPTOPACERASPIRE-E5471-006",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "2 GB",
		Internal:  "HDD: 320 GB",
		Lokasi:    "NURUL SPAREPART",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
	{
		ID:        bson.NewObjectID(),
		Nama:      "KOMPUTER SERVER BACKUP",
		Merk:      "RAKITAN",
		PC:        "PH1-CPUCOREI5-066",
		Monitor:   "-",
		CPU:       "Intel Core I3",
		RAM:       "4 GB",
		Internal:  "HDD: 8 TB",
		Lokasi:    "RUANG IT",
		Inserted:  doc.ByAt{At: time.Now(), ID: &SuperAdminID},
		IsDeleted: false,
	},
}
