package seed

import (
	"github.com/labstack/gommon/log"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"sipamit-be/api/device/repo"
	"sipamit-be/internal/pkg/doc"
	"time"
)

func Telepon(db *mongo.Database) {
	teleponRepo := repo.NewTeleponRepository(db)

	count, _ := teleponRepo.Count()
	if count > 0 {
		log.Info("Telepon already seeded")
		return
	}

	err := teleponRepo.InsertMany(telepons)
	if err != nil {
		log.Errorf("Failed to seed telepon: %v", err)
	}
	log.Info("Telepon seeded")
}

var telepons = []repo.Telepon{
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "UMUM",
		User:       "LINA",
		Ext:        "0",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "RISKA",
		Ext:        "118",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7220X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "VIOCHA",
		Ext:        "119",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "CHENEDY",
		Ext:        "115",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7250X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "DANIS",
		Ext:        "113",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7250X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "TEMMY",
		Ext:        "120",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "PETER",
		Ext:        "112",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "NATASHA",
		Ext:        "116",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "LUSI",
		Ext:        "317",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "NANCY",
		Ext:        "111",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7250X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "EXIM",
		User:       "MIA",
		Ext:        "114",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PPIC",
		User:       "ATIK/AYU",
		Ext:        "240",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "HRD",
		User:       "SUCI/RASMINI",
		Ext:        "122",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "HRD",
		User:       "MOELYONO",
		Ext:        "123",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "DIREKTUR",
		User:       "GIA",
		Ext:        "131",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7433X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PEMBELIAN",
		User:       "LILA",
		Ext:        "132",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},

	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PEMBELIAN",
		User:       "DHIMA",
		Ext:        "133",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PEMBELIAN",
		User:       "ELY/META",
		Ext:        "134",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PEMBELIAN",
		User:       "ANI/ETY/RICKY",
		Ext:        "135",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "PEMBELIAN",
		User:       "DESY/NIA",
		Ext:        "136",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "SPAREPART",
		User:       "NURUL",
		Ext:        "137",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "K3",
		User:       "LINDA",
		Ext:        "128",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "LABORATORIUM",
		User:       "LILIS",
		Ext:        "241",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "RINI",
		Ext:        "161",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXC",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "MS. MACHY",
		Ext:        "150",
		Merk:       "PANASONIC",
		Tipe:       "KX-T-7433X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "SUSWATI",
		Ext:        "151",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "ERNA",
		Ext:        "153",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "NORMA",
		Ext:        "154",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "ISROAH",
		Ext:        "155",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "IKA/EKA",
		Ext:        "159",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "DEWI/AZURA",
		Ext:        "156",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXC",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "DEVI/DILA",
		Ext:        "157",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "LILIS/ROHMA",
		Ext:        "160",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7220X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "ACCOUNTING",
		User:       "ERIZA/NENI",
		Ext:        "158",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "DESIGN",
		User:       "SUSI",
		Ext:        "144",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7220X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "DESIGN",
		User:       "ALUAN",
		Ext:        "141",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "DESIGN",
		User:       "WIWIK",
		Ext:        "145",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "DESIGN",
		User:       "RATNA/IZZA",
		Ext:        "142",
		Merk:       "SAHITEL",
		Tipe:       "S21W",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "OFFICE PRODUKSI",
		User:       "ROBBY",
		Ext:        "211",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXR",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "OFFICE PRODUKSI",
		User:       "LIA/KIKI",
		Ext:        "210",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "OFFICE PRODUKSI",
		User:       "IDA/ANIK",
		Ext:        "212",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "JAHIT KOMPUTER",
		User:       "AGUS/NINIK",
		Ext:        "215",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "BORDIR",
		User:       "WAHYU",
		Ext:        "310",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "GUDANG BAHAN",
		User:       "RINA/UMI",
		Ext:        "301",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "GUDANG BAHAN",
		User:       "ASTORINI",
		Ext:        "302",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "GUDANG OUTSOLE",
		User:       "TANTO",
		Ext:        "303",
		Merk:       "PANASONIC",
		Tipe:       "KX-TG6411CX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "GUDANG OUTSOLE",
		User:       "RENA",
		Ext:        "304",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7220X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "FOXING",
		User:       "ALAN/YULI",
		Ext:        "305",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "SABLON/FILM",
		User:       "INTAN/RENA",
		Ext:        "307",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7235X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "GUDANG JADI",
		User:       "MALA",
		Ext:        "316",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7235X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "POLIKLINIK",
		User:       "POLIKLINIK",
		Ext:        "126",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS3MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "HANGGAR BC",
		User:       "BEA CUKAI",
		Ext:        "124",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "POS SATPAM",
		User:       "POS SATPAM",
		Ext:        "125",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7250X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "BUYER",
		User:       "CRIME BU IRA",
		Ext:        "138",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "BUYER",
		User:       "CRIME DEVI/SONY",
		Ext:        "139",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH1",
		Departemen: "SATPAM UNIT",
		User:       "PLONG AB",
		Ext:        "214",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "LOBBY",
		User:       "LOBBY",
		Ext:        "0/201",
		Merk:       "PANASONIC",
		Tipe:       "KX-DT543",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "PEMBELIAN",
		User:       "AYU/FARISAH",
		Ext:        "-",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "CANTIKA/EVA",
		Ext:        "159",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXW",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "ALFY/AYU",
		Ext:        "111",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "AHUN",
		Ext:        "103",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "PEMBELIAN",
		User:       "DWI/NIKE/RESTU",
		Ext:        "112",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "PPIC",
		User:       "DELLA/HENI",
		Ext:        "106",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "SELVI/GIRINDRA",
		Ext:        "401",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "ELY",
		Ext:        "107",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "EXIM",
		User:       "ZAKIYA/LIA",
		Ext:        "114",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "HRD",
		User:       "WIWIK/FIFIN/MELATI",
		Ext:        "104",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MX",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "MR. BENZ",
		User:       "MR. BENZ",
		Ext:        "101",
		Merk:       "PANASONIC",
		Tipe:       "KX-TG6811CX2",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "MS. LIN-NAI",
		User:       "MS. LIN-NAI",
		Ext:        "102",
		Merk:       "PANASONIC",
		Tipe:       "KX-TG6811CX2",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "DESIGN",
		User:       "DESIGN",
		Ext:        "306",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "LASTING A",
		User:       "LASTING A",
		Ext:        "305",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "SATPAM PRODUKSI",
		User:       "SATPAM PRODUKSI",
		Ext:        "303",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "POS SATPAM",
		User:       "POS SATPAM",
		Ext:        "202",
		Merk:       "PANASONIC",
		Tipe:       "KX-TS505MXB",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
	{
		ID:         bson.NewObjectID(),
		Lokasi:     "PH2",
		Departemen: "BEA CUKAI",
		User:       "BEA CUKAI",
		Ext:        "",
		Merk:       "PANASONIC",
		Tipe:       "KX-T7450X",
		Inserted: doc.ByAt{
			At: time.Now(),
		},
		IsDeleted: false,
	},
}
